version: '3.8'

services:
  backend:
    image: ghcr.io/datacanvas-iot/datacanvas-back:latest
    container_name: datacanvas-backend
    env_file:
      - backend.env
    restart: unless-stopped
    networks:
      - datacanvas-network
    expose:
      - "8000"

  frontend:
    image: ghcr.io/datacanvas-iot/datacanvas-front:latest
    container_name: datacanvas-frontend
    env_file:
      - frontend.env
    restart: unless-stopped
    networks:
      - datacanvas-network
    ports:
      - "3000:3000"

networks:
  datacanvas-network:
    driver: bridge